name: Data Feeds - Run Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18

      - name: Install application dependencies
        run: npm ci
        working-directory: .

      - name: Check code passes the unit tests
        run: npm run test
        working-directory: .
        env:
          WEBHOOK_URL: https://webhook.site/6b495c5d-95b3-40b1-b85d-49dcf76a3d44
